#!/bin/bash
#PBS -N ancestor_tree
#PBS -m abe
#PBS -M "schaefce@miamioh.edu"
#PBS -l nodes=1:ppn=8
#PBS -l walltime=2:0:0


cd ~/karro/gene_block_evolution

module load python-2.7.6

if [ -z $gb ]; then
    gb="optimized_operon/paaABCDEFGHIJK.txt"
fi

if [ -z $tree ]; then
    tree="reorder.nwk"
fi

if [ -z $ids ]; then
    ids="mapping.csv"
fi

if [ -n "$mg" ]; then
    MG="--max_gap ${mg}"
else
    MG=""
fi

if [ -n "$npr" ]; then   
    PR="--no_prune"
else
    PR=""
fi

echo "${MG} ${PR} ${gb} ${tree} ${ids}" 

python2.7 label_ancestors2.py ${MG} ${PR} ${gb} ${tree} ${ids} #${MG} ${PR} #optimized_operon/paaABCDEFGHIJK.txt reorder.nwk mapping.csv 

